export default {
  at: '2024-07-09T23:08:59.698Z',
  products: [
    {
      description: 'proident occaecat in exercitation',
      name: 'Lorem',
      price: 1796.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {
      description: 'veniam nulla deserunt duis',
      name: 'adipisicing',
      price: 770.62,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: 'dolor in esse ut',
      name: 'commodo',
      price: 434.66,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {},
    {},
    {},
    {
      description: 'sit labore et ea',
      name: 'aliquip',
      price: 122.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nisi Lorem ea esse',
      name: 'eiusmod',
      price: 396.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo et irure et',
      name: 'labore',
      price: 597.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eiusmod irure veniam occaecat',
      name: 'aliqua',
      price: 1564.98,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: 'eu labore elit nostrud',
      name: 'in',
      price: 985.31,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: 'non enim minim magna',
      name: 'aliqua',
      price: 1927.04,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: 'aliquip pariatur dolor commodo',
      name: 'sunt',
      price: 447.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'Lorem eu excepteur consequat',
      name: 'incididunt',
      price: 553.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'minim sint nostrud sunt',
      name: 'et',
      price: 1378.71,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: 'excepteur pariatur deserunt minim',
      name: 'ad',
      price: 1181.62,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ut nisi magna exercitation',
      name: 'cupidatat',
      price: 348.77,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: 'duis consequat velit irure',
      name: 'sit',
      price: 1314.9,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: 'Lorem amet voluptate et',
      name: 'officia',
      price: 953.36,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: 'aliquip ut adipisicing esse',
      name: 'duis',
      price: 1621.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'reprehenderit elit magna id',
      name: 'tempor',
      price: 1519.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'do laborum fugiat eu',
      name: 'aliquip',
      price: 1781.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo esse proident aliqua',
      name: 'anim',
      price: 566.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'in est ex fugiat',
      name: 'sint',
      price: 1251.5,
      tmpProperty: undefined,
      activePromoId: 27,
    },
    {
      description: 'sit incididunt dolore deserunt',
      name: 'est',
      price: 563.9,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: 'esse officia cillum nisi',
      name: 'consectetur',
      price: 160.5,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'adipisicing est aliqua culpa',
      name: 'id',
      price: 1931.95,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: 'quis nulla non sit',
      name: 'culpa',
      price: 1093.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laboris aliquip dolore est',
      name: 'dolore',
      price: 1440.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore dolor consequat ad',
      name: 'magna',
      price: 1832.03,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: 'elit do do tempor',
      name: 'fugiat',
      price: 1891.64,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: 'excepteur culpa officia nostrud',
      name: 'commodo',
      price: 122.71,
      tmpProperty: undefined,
      activePromoId: 20,
    },
    {
      description: 'nostrud est enim nostrud',
      name: 'cillum',
      price: 1335.8,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'ea proident nostrud laboris',
      name: 'mollit',
      price: 1574.05,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: 'laborum non et ullamco',
      name: 'ad',
      price: 1240.45,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis adipisicing exercitation pariatur',
      name: 'ad',
      price: 676.7,
      tmpProperty: undefined,
      activePromoId: 84,
    },
    {
      description: 'nostrud amet anim ullamco',
      name: 'ut',
      price: 1456.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'incididunt ullamco aute non',
      name: 'quis',
      price: 152.66,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: 'nisi cillum ullamco ipsum',
      name: 'irure',
      price: 1711.78,
      tmpProperty: undefined,
      activePromoId: 20,
    },
    {
      description: 'eu ex nulla ad',
      name: 'qui',
      price: 590.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nisi velit id et',
      name: 'id',
      price: 1137.95,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: 'mollit cillum qui do',
      name: 'cillum',
      price: 394.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'adipisicing sint magna culpa',
      name: 'adipisicing',
      price: 1056.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'qui dolore sint magna',
      name: 'amet',
      price: 1001.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'reprehenderit qui et enim',
      name: 'pariatur',
      price: 207.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat ex sit ea',
      name: 'amet',
      price: 993.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'est excepteur sint consectetur',
      name: 'occaecat',
      price: 1819.54,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: 'aliquip sunt sit adipisicing',
      name: 'mollit',
      price: 888.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'voluptate qui velit ex',
      name: 'aliquip',
      price: 1916.7,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: 'ea dolor consequat occaecat',
      name: 'velit',
      price: 1178.89,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'cillum id ullamco incididunt',
      name: 'adipisicing',
      price: 883.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse pariatur ullamco exercitation',
      name: 'eu',
      price: 123.05,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua aliqua pariatur mollit',
      name: 'occaecat',
      price: 1489.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'amet do reprehenderit ullamco',
      name: 'aute',
      price: 1216.41,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: 'reprehenderit sint elit id',
      name: 'Lorem',
      price: 1231.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eiusmod nulla exercitation deserunt',
      name: 'quis',
      price: 274.35,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: 'ullamco esse excepteur tempor',
      name: 'est',
      price: 1909.8,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: 'irure tempor exercitation adipisicing',
      name: 'irure',
      price: 1081.73,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: 'eu laborum eiusmod ea',
      name: 'commodo',
      price: 1625.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation elit cillum est',
      name: 'id',
      price: 1108.18,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: 'fugiat exercitation eu aliqua',
      name: 'enim',
      price: 372.58,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: 'enim commodo occaecat est',
      name: 'commodo',
      price: 1188.99,
      tmpProperty: undefined,
      activePromoId: 69,
    },
    {
      description: 'excepteur voluptate voluptate exercitation',
      name: 'aute',
      price: 207.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eiusmod elit qui quis',
      name: 'anim',
      price: 1122.64,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: 'voluptate et Lorem voluptate',
      name: 'elit',
      price: 1197.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aute irure tempor nulla',
      name: 'ex',
      price: 1377.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'adipisicing dolore sunt cupidatat',
      name: 'veniam',
      price: 570.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolor est velit ut',
      name: 'ullamco',
      price: 319.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco qui non sit',
      name: 'minim',
      price: 415.71,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: 'duis sit dolor deserunt',
      name: 'cupidatat',
      price: 837.58,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: 'reprehenderit mollit cupidatat quis',
      name: 'veniam',
      price: 805.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat culpa fugiat irure',
      name: 'est',
      price: 1694.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'voluptate nostrud dolor voluptate',
      name: 'labore',
      price: 1374.08,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: 'qui occaecat quis nisi',
      name: 'dolore',
      price: 1173.06,
      tmpProperty: undefined,
      activePromoId: 80,
    },
    {
      description: 'commodo laborum veniam sunt',
      name: 'quis',
      price: 896.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ipsum esse pariatur adipisicing',
      name: 'eiusmod',
      price: 1214.51,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: 'tempor pariatur cillum non',
      name: 'quis',
      price: 896.04,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: 'cillum culpa et aliqua',
      name: 'elit',
      price: 729.53,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: 'excepteur commodo sint anim',
      name: 'occaecat',
      price: 172.66,
      tmpProperty: undefined,
      activePromoId: 58,
    },
    {
      description: 'dolor minim veniam velit',
      name: 'pariatur',
      price: 1073.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'culpa Lorem et pariatur',
      name: 'amet',
      price: 1774.95,
      tmpProperty: undefined,
      activePromoId: 50,
    },
    {
      description: 'eiusmod fugiat magna officia',
      name: 'in',
      price: 984.01,
      tmpProperty: undefined,
      activePromoId: 31,
    },
    {
      description: 'aliquip irure eiusmod deserunt',
      name: 'duis',
      price: 1441.64,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim cupidatat esse amet',
      name: 'id',
      price: 392.05,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'labore esse ut ea',
      name: 'sunt',
      price: 634.34,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: 'culpa consectetur id fugiat',
      name: 'aute',
      price: 497.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolor enim cupidatat pariatur',
      name: 'ad',
      price: 1561.71,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: 'anim eiusmod sint exercitation',
      name: 'esse',
      price: 1046.21,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: 'consectetur fugiat dolore sit',
      name: 'proident',
      price: 949.68,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'reprehenderit deserunt ut deserunt',
      name: 'mollit',
      price: 1527.34,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: 'cillum fugiat consectetur pariatur',
      name: 'ad',
      price: 1110.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'minim do labore culpa',
      name: 'nostrud',
      price: 584.8,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: 'excepteur officia labore aliquip',
      name: 'excepteur',
      price: 423.99,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: 'sint dolore laborum eu',
      name: 'esse',
      price: 891.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'excepteur et culpa adipisicing',
      name: 'culpa',
      price: 418.3,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad est anim pariatur',
      name: 'nulla',
      price: 1612.37,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sit reprehenderit sit irure',
      name: 'sunt',
      price: 1146.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sunt minim ipsum sit',
      name: 'labore',
      price: 1258.28,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: 'id nisi excepteur aliqua',
      name: 'dolor',
      price: 1788.26,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: 'nostrud commodo amet culpa',
      name: 'sit',
      price: 1291.02,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: 'consectetur pariatur ea consequat',
      name: 'qui',
      price: 330.26,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: 'aliqua incididunt est amet',
      name: 'dolor',
      price: 515.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: 'enim elit commodo mollit',
      name: 'incididunt',
      price: 306.14,
      tmpProperty: undefined,
      activePromoId: 0,
    },
  ],
};
